### ISSUE TITLE
Setting Parameter from audioProcessor

### ISSUE THREAD

**Issue by davispolito** [Chowdhury-DSP/chowdsp_utils#571]
I'm trying to understand how I could set a value from the audio processor using the paramholder and slider attachment without it being thread-unsafe / blocking. The only input I have into a parameter on the audio processor side is the setParameterValue() which clearly states that it calls setvaluenotifyinghost which is a function that could be blocking.. 

am I missing something or am I simply trying to misuse the processorparams? 

I am basically just trying to use a Velocity Parameter attached to a slider to display the most recent velocity

**Comment by davispolito** [comment]
it appears thread safe since in the actual paramtervaluechanged code we exit if we aren't on the message thread... but your comment about calling setvaluenotifyinghost scares me lol.

**Comment by jatinchowdhury18** [comment]
Unfortunately, looking at the `parameterValueChanged()` code in this repository is not enough to confirm that setting a parameter value from the audio thread will be real-time safe. Other JUCE code can also use `AudioProcessorParameter::Listener`s, for example JUCE's plugin wrappers (here's [VST3](https://github.com/juce-framework/JUCE/blob/51d11a2be6d5c97ccf12b4e5e827006e19f0555a/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp#L1490) and [AU](https://github.com/juce-framework/JUCE/blob/51d11a2be6d5c97ccf12b4e5e827006e19f0555a/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU_1.mm#L133)). It should be possible to confirm whether these other parameter listeners are going to be real-time safe or not, but it will require a more thorough investigation.

That said, if I understand what you're trying to do here (display the most recent note velocity in the UI), I would highly recommend not using a parameter for this purpose. I typically only use parameters for things the DAW should know about (for automation purposes, etc). If the DAW doesn't need to know about it, it's almost always simpler to use some other mechanism.

For visualizations, I usually use one of two approaches:
1. Create an atomic variable. Write to the variable on the audio thread. Set up a timer on the UI thread that reads the latest value from the variable and updates the display.
2. Send data from the audio thread to the UI thread via lock-free queue. Pull the data out of the queue on the UI thread, and update the display.

Option 1 is usually easier, but there are some instances where option 2 makes more sense.
